name: 'Pull request backport via label'
description: 'Backport pull request based on backport label'
branding:
  icon: corner-left-down
  color: gray-dark
inputs:
  token:
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: 'docker'
  image: 'Dockerfile'
