name: Backport

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    name: Backport closed pull request
    steps:
    - uses: syndesisio/backport-action@master
